tests

diff --git a/.github/workflows/docker.yaml b/.github/workflows/docker.yaml
--- a/.github/workflows/docker.yaml
+++ b/.github/workflows/docker.yaml
@@ -142,9 +142,15 @@ jobs:
           # trivy-config: .trivy.yaml
           ignore-unfixed: false
 
+      - name: Upload scan results
+        uses: actions/upload-artifact@v3
+        # if: success() || failure()
+        with:
+          name: container-scan-results-json
+          path: scan-results.json
 
       - name: Extract high and critical vulnerabilities
-        id: extract_vulnerabilities
+        id: extract_vulnerabilities_orig
         run: |
           jq -r '
           def hr(severity):
@@ -157,11 +163,36 @@ jobs:
           "## High and Critical Vulnerabilities",
           "",
           "| Vulnerability ID | Package | Version | Severity | Description |",
-          "| — — — — — — — — — | — — — — -| — — — — -| — — — — — | — — — — — — -|",
+          "| - - - - - - - - - | - - - - -| - - - - -| - - - - - | - - - - - - -|",
           (.Results[] | .Vulnerabilities[] | select(hr(.Severity)) | to_md),
           ""
           ] | join("\n")
           'scan-results.json > vulnerability-report.md
+
+
+
+
+      - name: Extract high and critical vulnerabilities
+        if: success() || failure()
+        id: extract_vulnerabilities_1
+        run: |
+          jq -r '
+          def hr(severity):
+          if severity == "HIGH" or severity == "CRITICAL" then true else false end;
+          def to_md:
+          "| " + (.VulnerabilityID // "") + " | " + (.PkgName // "") + " | " + (.InstalledVersion // "") + " | " + (.Severity // "") + " | " + (.Title // "") + " |";
+          [
+          "# Docker Image Scan Results",
+          "",
+          "## High and Critical Vulnerabilities",
+          "",
+          "| Vulnerability ID | Package | Version | Severity | Description |",
+          "| - - - - - - - - - | - - - - -| - - - - -| - - - - - | - - - - - - -|",
+          (.Results[] | .Vulnerabilities[] | select(hr(.Severity)) | to_md),
+          ""
+          ] | join("\n")
+          '
+
 
 
       - name: Capture scan results
